### ISSUE TITLE
 Morning Session Team - P2P CR - Module 1 - Week 4

### ISSUE THREAD

**Issue by ramiaquista** [dicodiaz/portfolio-first-draft#17]

**Comment by ramiaquista** [comment]
## Awesome Job! 🔨

#### I think it would be a great idea if you can avoid wrapping the contact form sections into li tags. 

![Screen Shot 2021-09-02 at 11 22 23 AM](https://user-images.githubusercontent.com/24655018/131861044-61d4e5f0-bd7c-4587-8c4f-7e10d78d64c7.png)

Keep coding, you are making awesome things! 😄  

![cat-gif](https://camo.githubusercontent.com/ad1cd31d21b84078086e8649cd649f282fff8e3ee6636875934569562d21c8d6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f3156694c7030474259685463412f67697068792e676966)

**Comment by mike2611** [comment]
# Great code :+1: 
## I have a suggestion for using global variables is best practice to use global variables only when are necessary. Try to keep the scope of your variables inside the function. https://www.freecodecamp.org/news/global-variables-in-javascript-explained/
# :robot:

**Comment by KatIsCoding** [comment]
# Nice project!
----
### Overall I really like your project, is functional and works great, however, I found some things that might make your project look better!😎

## Mobile Menu Animations
----
### Your mobile menu works great so far but I think it still needs some animations so it is more pleasant to the eye! So what about adding a transition/animation to the mobile menu? Maybe making it appear from the top or one of the sides! 🤩

## Scrolling
----
### I see how your menu links correctly redirect to a specific section in your page but they do in an instantaneous way which might not look that great to the end user, so what about adding some scrolling to your page so everything looks slick and cool!🔥🚀

```css
/*Hint*/
scroll-behavior: ?;
```
----

## Hopefully your project will look even better after these changes!! Have a great day/night!
![Gif](https://c.tenor.com/PWm8z5W5tNEAAAAd/cat-blep-cat-tongue.gif)

**Comment by dicodiaz** [comment]
> # Great code 👍
> ## I have a suggestion for using global variables is best practice to use global variables only when are necessary. Try to keep the scope of your variables inside the function. https://www.freecodecamp.org/news/global-variables-in-javascript-explained/
> # 🤖

Hey, thanks for your suggestion! But I'm having a hard time understanding something: The article says that "If you declare a variable without using var, even if it’s inside a function, it will still be seen as global", so if I use const inside a function it will still be global, right? I tried using var but Eslint won't let me because I never update the value of the variable, so it forces me to change it to const. So that means it makes no difference if I define it inside or outside of the function. Please correct me if I'm wrong.

**Comment by dicodiaz** [comment]
Thanks for your suggestion, guys! I applied them all.
