### ISSUE TITLE
Not an issue but an observation.

### ISSUE THREAD

**Issue by sergiogval** [dicodiaz/portfolio-first-draft#6]
I will only do some recommendations about the disruptive changes that your web page shows once you reach the break point. That said, I believe that you made a great job. 
Congrats!

- [ ] Check the way to do transitions smoothly and implement if you feel like.

**Comment by dicodiaz** [comment]
Thanks! I think those disruptive changes are acceptable because the user won't be changing the screen size - They will only open the page with a specific screen size so they won't notice any disruptive changes.
